<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Product;
use App\Models\Brand;
use App\Models\Type;
use App\Models\ProductCategory;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $typesCategories = [
            'Skincare' => [
                'Limpiadores' => [
                    'description' => 'Productos diseñados para limpiar la piel, eliminando impurezas, maquillaje y exceso de sebo sin resecar.',
                    'products' => [
                        [
                            'name' => 'CeraVe Hydrating Cleanser',
                            'brand_id' => 1,
                            'image' => 'CeraVeHydratingCleanser.webp',
                            'description' => 'Limpiador hidratante que respeta la barrera cutánea. Ideal para piel normal a seca.',
                            'ingredients' => 'Aqua, Glycerin, Ceramides, Hyaluronic Acid',
                            'activos' => 'Ceramidas, Ácido Hialurónico',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2],
                            'concerns' => [1, 7, 8, 9],
                        ],
                        [
                            'name' => 'La Roche-Posay Effaclar Gel',
                            'brand_id' => 2,
                            'image' => 'imagen3_la_roche_posay_effaclar_gel_moussant_purificante_x_400ml_imagen3.jpg',
                            'description' => 'Gel limpiador para piel grasa y con tendencia acnéica. Limpia suavemente sin resecar.',
                            'ingredients' => 'Aqua, Zinc PCA, Glycerin, Coco-Betaine',
                            'activos' => 'Zinc PCA',
                            'formato' => 'Gel',
                            'rating' => 4,
                            'skin_types' => [3, 5],
                            'concerns' => [1, 2, 8, 9],
                        ],
                        [
                            'name' => 'Neutrogena Hydro Boost Water Gel Cleanser',
                            'brand_id' => 3,
                            'image' => 'neutrogena-hydro-boost-cleanser-water-gel-200ml_2.webp',
                            'description' => 'Limpiador en gel ligero que hidrata y refresca, no comedogénico.',
                            'ingredients' => 'Water, Glycerin, Dimethicone, Hyaluronic Acid',
                            'activos' => 'Ácido Hialurónico',
                            'formato' => 'Gel',
                            'rating' => 5,
                            'skin_types' => [1, 2, 5],
                            'concerns' => [1, 8],
                        ],
                        [
                            'name' => 'Icono Cosmetica Gel de Limpieza Facial Purificante',
                            'brand_id' => 8,
                            'image' => 'icono.jpg',
                            'description' => 'Gel de limpieza purificante para pieles mixtas a grasas. Formulación con activos botánicos.',
                            'ingredients' => 'Extracto de Hamamelis, Tensioactivos suaves',
                            'activos' => 'Hamamelis, Zinc',
                            'formato' => 'Gel',
                            'rating' => 4,
                            'skin_types' => [1, 3, 4],
                            'concerns' => [1, 8],
                        ],
                        [
                            'name' => 'CeraVe Foaming Facial Cleanser',
                            'brand_id' => 1,
                            'image' => 'cerave-foaming-cleanser.jpg',
                            'description' => 'Limpiador espumoso para piel normal a grasa, elimina exceso de sebo sin alterar barrera.',
                            'ingredients' => 'Aqua, Cocamidopropyl Hydroxysultaine, Glycerin, Ceramides',
                            'activos' => 'Ceramidas, Niacinamida',
                            'formato' => 'Gel',
                            'rating' => 5,
                            'skin_types' => [3, 4],
                            'concerns' => [1, 2, 8],
                        ],
                        [
                            'name' => 'Bioderma Sensibio H2O Micellar Water',
                            'brand_id' => 21,
                            'image' => 'bioderma-sensibio-h2o.png',
                            'description' => 'Agua micelar para piel sensible, limpia e hidrata sin enjuague.',
                            'ingredients' => 'Aqua, Glycerin, Micelas',
                            'activos' => 'Micelas suaves',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [5],
                            'concerns' => [1, 9],
                        ],
                        [
                            'name' => 'La Roche-Posay Toleriane Caring Wash',
                            'brand_id' => 2,
                            'image' => 'toleriane-caring-wash.png',
                            'description' => 'Limpiador suave para piel sensible con prebióticos.',
                            'ingredients' => 'Aqua, Glycerin, Ceramides',
                            'activos' => 'Prebióticos',
                            'formato' => 'Gel',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [1, 9],
                        ],
                        [
                            'name' => 'Avène Cleanance Cleansing Gel',
                            'brand_id' => 20,
                            'image' => 'avene-cleanance-gel.png',
                            'description' => 'Gel limpiador para piel grasa/acnéica con agua termal.',
                            'ingredients' => 'Aqua Termal, Monolaurina',
                            'activos' => 'Agua termal',
                            'formato' => 'Gel',
                            'rating' => 4,
                            'skin_types' => [3, 4],
                            'concerns' => [1, 2],
                        ],
                        [
                            'name' => 'Cetaphil Gentle Skin Cleanser',
                            'brand_id' => 19,
                            'image' => 'cetaphil-gentle-cleanser.png',
                            'description' => 'Limpiador suave sin jabón para piel sensible.',
                            'ingredients' => 'Aqua, Glycerin',
                            'activos' => 'Sin fragancia',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2, 5],
                            'concerns' => [1, 9],
                        ],
                        [
                            'name' => 'Eucerin DermatoCLEAN Cleansing Gel',
                            'brand_id' => 11,
                            'image' => 'eucerin-dermatoclean.jpg',
                            'description' => 'Gel limpiador suave para piel seca/sensible.',
                            'ingredients' => 'Aqua, Glycerin',
                            'activos' => 'pH 5',
                            'formato' => 'Gel',
                            'rating' => 4,
                            'skin_types' => [2, 5],
                            'concerns' => [1, 3],
                        ],
                    ],
                ],
                'Hidratantes' => [
                    'description' => 'Productos formulados para hidratar la piel, restaurar la barrera cutánea y mantener la humectación.',
                    'products' => [
                        [
                            'name' => 'La Roche-Posay Toleriane Double Matt Repair Moisturizer',
                            'brand_id' => 2,
                            'image' => 'matt.jpg',
                            'description' => 'Hidratante para piel sensible con ceramidas y niacinamida. Restaura la barrera protectora.',
                            'ingredients' => 'Aqua, Glycerin, Ceramides, Niacinamide',
                            'activos' => 'Ceramidas, Niacinamida',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [3, 4, 5],
                            'concerns' => [1, 8, 9],
                        ],
                        [
                            'name' => 'CeraVe Crema Hidratante',
                            'brand_id' => 1,
                            'image' => 'ceravee.jpeg',
                            'description' => 'Crema densa para cuerpo y rostro. Hidratación 24 horas con 3 ceramidas esenciales.',
                            'ingredients' => 'Aqua, Glycerin, Ceramides, Petrolatum',
                            'activos' => 'Ceramidas, Ácido Hialurónico',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2],
                            'concerns' => [3, 9],
                        ],
                        [
                            'name' => 'The Ordinary Natural Moisturizing Factors + HA',
                            'brand_id' => 9,
                            'image' => 'the-ordinary-natural-moisturizing-factors-ha-100ml.avif',
                            'description' => 'Fórmula no grasa que ofrece hidratación superficial con Factores Hidratantes Naturales.',
                            'ingredients' => 'Amino Acids, Dermal Lipids, Hyaluronic Acid, Glycerin',
                            'activos' => 'Factores de Humectación Natural, Ácido Hialurónico',
                            'formato' => 'Loción',
                            'rating' => 4,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [7, 10],
                        ],
                        [
                            'name' => 'Dermaglós Facial Crema Nutritiva de Noche',
                            'brand_id' => 10,
                            'image' => 'dermaglos.webp',
                            'description' => 'Crema nutritiva para la noche con Vitamina A. Mejora la elasticidad y regeneración celular.',
                            'ingredients' => 'Vitamina A, Alantoína, Glicerina',
                            'activos' => 'Vitamina A',
                            'formato' => 'Loción',
                            'rating' => 4,
                            'skin_types' => [1, 2, 5],
                            'concerns' => [3, 10],
                        ],
                        [
                            'name' => 'La Roche-Posay Toleriane Double Repair Face Moisturizer',
                            'brand_id' => 2,
                            'image' => 'toleriane-double-repair.webp',
                            'description' => 'Crema reparadora diaria con prebiótico, ceramidas y niacinamida para piel sensible.',
                            'ingredients' => 'Ceramides, Niacinamide, Prebiotic Thermal Water',
                            'activos' => 'Ceramidas, Niacinamida',
                            'formato' => 'Crema',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 9],
                        ],
                        [
                            'name' => 'Aestura Atobarrier365 Cream',
                            'brand_id' => 28,
                            'image' => 'aestura-atobarrier.png',
                            'description' => 'Crema barrera intensiva para piel seca/irritada con ceramidas.',
                            'ingredients' => 'Ceramides, Fatty Acids',
                            'activos' => 'Complejo barrera',
                            'formato' => 'Crema',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 9],
                        ],
                        [
                            'name' => 'Nécessaire The Body Lotion',
                            'brand_id' => 23,
                            'image' => 'necessaire-body-lotion.png',
                            'description' => 'Loción ligera con niacinamida para hidratación diaria.',
                            'ingredients' => 'Niacinamide, Hyaluronic Acid',
                            'activos' => 'Niacinamida',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [3, 7],
                        ],
                    ],
                ],
                'Protectores Solares' => [
                    'description' => 'Productos diseñados para proteger la piel de los daños causados por la radiación UV.',
                    'products' => [
                        [
                            'name' => 'Eucerin Sun Fluid Photoaging Control FPS 50',
                            'brand_id' => 11,
                            'image' => 'eucerin.webp',
                            'description' => 'Protector solar facial de amplio espectro, con ácido hialurónico para reducir arrugas.',
                            'ingredients' => 'Filtros UVA/UVB, Licochalcona A, Ácido Glicirretínico',
                            'activos' => 'FPS 50+, Ácido Hialurónico',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [2, 3],
                        ],
                        [
                            'name' => 'Isdin Fusion Water Magic FPS 50',
                            'brand_id' => 12,
                            'image' => 'isdin.jpg',
                            'description' => 'Protector facial ultraligero a base de agua, de absorción inmediata.',
                            'ingredients' => 'Aqua, Filtros solares, Ácido Hialurónico',
                            'activos' => 'FPS 50, Tecnología Safe-Eye',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [2, 3],
                        ],
                        [
                            'name' => 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF50+',
                            'brand_id' => 2,
                            'image' => 'anthelios-uvmune.webp',
                            'description' => 'Fluido invisible con protección ultra amplia contra UVA largos.',
                            'ingredients' => 'Mexoryl 400, Netlock Technology',
                            'activos' => 'FPS 50+, Mexoryl',
                            'formato' => 'Fluido',
                            'rating' => 5,
                            'skin_types' => [1, 3, 4, 5],
                            'concerns' => [2, 3],
                        ],
                        [
                            'name' => 'EltaMD UV Clear Broad-Spectrum SPF 46',
                            'brand_id' => 22,
                            'image' => 'eltamd-uv-clear.jpg',
                            'description' => 'Protector mineral con niacinamida para piel sensible/acnéica.',
                            'ingredients' => 'Zinc Oxide, Niacinamide',
                            'activos' => 'FPS 46, Niacinamida',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [3, 4, 5],
                            'concerns' => [2, 8],
                        ],
                        [
                            'name' => 'Aveeno Protect + Hydrate Sunscreen Lotion SPF 60',
                            'brand_id' => 24,
                            'image' => 'aveeno-protect-hydrate.png',
                            'description' => 'Loción hidratante con avena para uso diario en cuerpo y rostro.',
                            'ingredients' => 'Avobenzone, Homosalate, Oat Extract',
                            'activos' => 'FPS 60',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [1, 2, 5],
                            'concerns' => [2, 3],
                        ],
                    ],
                ],
                'Sérums' => [
                    'description' => 'Productos de alta concentración para tratar preocupaciones específicas.',
                    'products' => [
                        [
                            'name' => 'Vichy Mineral 89 Booster',
                            'brand_id' => 13,
                            'image' => 'vichy.webp',
                            'description' => 'Concentrado fortificante con 89% Agua Volcánica y Ácido Hialurónico.',
                            'ingredients' => 'Aqua Volcánica de Vichy, Ácido Hialurónico',
                            'activos' => 'Ácido Hialurónico, Minerales',
                            'formato' => 'Sérum',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [1, 3, 9, 5],
                        ],
                        [
                            'name' => 'The Ordinary Niacinamide 10% + Zinc 1%',
                            'brand_id' => 9,
                            'image' => 'ordinary.webp',
                            'description' => 'Sérum para reducir manchas, poros e imperfecciones.',
                            'ingredients' => 'Niacinamide, Zinc PCA',
                            'activos' => 'Niacinamida 10%, Zinc 1%',
                            'formato' => 'Sérum',
                            'rating' => 4,
                            'skin_types' => [3, 4],
                            'concerns' => [1, 5, 8],
                        ],
                        [
                            'name' => 'Glow Factor Vitamina C 15%',
                            'brand_id' => 14,
                            'image' => 'glowfact.webp',
                            'description' => 'Sérum de Vitamina C pura para acción antioxidante e iluminadora.',
                            'ingredients' => 'Sodium Ascorbate, Ferulic Acid',
                            'activos' => 'Vitamina C, Ácido Ferúlico',
                            'formato' => 'Sérum',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [3, 6, 2, 5],
                        ],
                        [
                            'name' => 'SkinCeuticals C E Ferulic',
                            'brand_id' => 25,
                            'image' => 'skinceuticals-ce-ferulic.webp',
                            'description' => 'Sérum antioxidante con 15% Vitamina C, Vitamina E y Ácido Ferúlico.',
                            'ingredients' => 'L-Ascorbic Acid 15%, Vitamin E, Ferulic Acid',
                            'activos' => 'Vitamina C 15%',
                            'formato' => 'Sérum',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [3, 6, 10],
                        ],
                        [
                            'name' => 'COSRX The Niacinamide 15 Serum',
                            'brand_id' => 27,
                            'image' => 'cosrx-niacinamide-15.png',
                            'description' => 'Sérum alta concentración niacinamida para control de sebo y manchas.',
                            'ingredients' => 'Niacinamide 15%, Zinc PCA',
                            'activos' => 'Niacinamida 15%',
                            'formato' => 'Sérum',
                            'rating' => 5,
                            'skin_types' => [3, 4],
                            'concerns' => [2, 5, 8],
                        ],
                    ],
                ],
                'Exfoliantes' => [
                    'description' => 'Productos para eliminar células muertas y mejorar textura.',
                    'products' => [
                        [
                            'name' => 'Paula\'s Choice 2% BHA Liquid Exfoliant',
                            'brand_id' => 15,
                            'image' => 'paulas.webp',
                            'description' => 'Exfoliante químico con ácido salicílico para desobstruir poros.',
                            'ingredients' => 'Salicylic Acid (BHA), Green Tea Extract',
                            'activos' => 'Ácido Salicílico 2%',
                            'formato' => 'Líquido',
                            'rating' => 5,
                            'skin_types' => [3, 4],
                            'concerns' => [1, 8],
                        ],
                        [
                            'name' => 'The Ordinary Glycolic Acid 7% Toning Solution',
                            'brand_id' => 9,
                            'image' => 'ordinary-glycolic-toner.webp',
                            'description' => 'Tónico exfoliante AHA para luminosidad y textura suave.',
                            'ingredients' => 'Glycolic Acid 7%, Tasmanian Pepperberry',
                            'activos' => 'Ácido Glicólico 7%',
                            'formato' => 'Tónico',
                            'rating' => 4,
                            'skin_types' => [1, 3, 4],
                            'concerns' => [8, 10],
                        ],
                    ],
                ],
            ],
            'Haircare' => [
                'Shampoo' => [
                    'description' => 'Productos para limpiar cuero cabelludo y cabello.',
                    'products' => [
                        [
                            'name' => 'Kérastase Resistance Bain Force Architecte',
                            'brand_id' => 5,
                            'image' => 'bain-force-architecte-resistance-250ml-01-kerastase.webp',
                            'description' => 'Shampoo reparador para cabellos dañados.',
                            'ingredients' => 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Proteínas',
                            'activos' => 'Ceramidas, Proteínas',
                            'formato' => '250ml',
                            'rating' => 5,
                            'skin_types' => [1, 2, 4],
                            'concerns' => [11, 12],
                        ],
                        [
                            'name' => 'L’Oréal Serie Expert Absolut Repair',
                            'brand_id' => 6,
                            'image' => 'loreal.webp',
                            'description' => 'Shampoo nutritivo para cabello muy dañado con Quinoa Dorada.',
                            'ingredients' => 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Lipidos',
                            'activos' => 'Quinoa Dorada, Proteínas',
                            'formato' => '300ml',
                            'rating' => 5,
                            'skin_types' => [1, 4],
                            'concerns' => [12],
                        ],
                        [
                            'name' => 'Capilatis Ortiga Shampoo para Cabellos Grasos',
                            'brand_id' => 16,
                            'image' => 'capilatis1.jpg',
                            'description' => 'Shampoo con extracto de Ortiga para regular sebo.',
                            'ingredients' => 'Extracto de Ortiga, Tensoactivos suaves',
                            'activos' => 'Extracto de Ortiga',
                            'formato' => '420ml',
                            'rating' => 4,
                            'skin_types' => [3],
                            'concerns' => [],
                        ],
                        [
                            'name' => 'Nizoral Anti-Dandruff Shampoo 1% Ketoconazole',
                            'brand_id' => 31,
                            'image' => 'nizoral-shampoo.jpg',
                            'description' => 'Shampoo medicado contra caspa y dermatitis seborreica.',
                            'ingredients' => 'Ketoconazole 1%',
                            'activos' => 'Ketoconazol',
                            'formato' => '200ml',
                            'rating' => 5,
                            'skin_types' => [1, 3],
                            'concerns' => [13],
                        ],
                        [
                            'name' => 'Vegamour GRO+ Advanced Balancing Shampoo',
                            'brand_id' => 30,
                            'image' => 'vegamour-gro-shampoo.webp',
                            'description' => 'Shampoo estimulante para cabello fino y caída.',
                            'ingredients' => 'Mung Bean, Red Clover',
                            'activos' => 'Fito-activos',
                            'formato' => '250ml',
                            'rating' => 4,
                            'skin_types' => [1],
                            'concerns' => [14],
                        ],
                        [
                            'name' => 'Olaplex No.4 Bond Maintenance Shampoo',
                            'brand_id' => 17,
                            'image' => 'olaplex-no4.webp',
                            'description' => 'Shampoo reparador de enlaces para cabello dañado.',
                            'ingredients' => 'Bis-Aminopropyl Diglycol Dimaleate',
                            'activos' => 'Tecnología Bond Building',
                            'formato' => '250ml',
                            'rating' => 5,
                            'skin_types' => [1, 4],
                            'concerns' => [11, 12],
                        ],
                    ],
                ],
                'Acondicionador' => [
                    'description' => 'Productos para hidratar y desenredar después del shampoo.',
                    'products' => [
                        [
                            'name' => 'Redken Extreme Conditioner',
                            'brand_id' => 7,
                            'image' => 'redken-extreme-conditioner-2021.webp',
                            'description' => 'Acondicionador fortalecedor para cabello débil.',
                            'ingredients' => 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Proteínas',
                            'activos' => 'Proteínas, Ceramidas',
                            'formato' => '250ml',
                            'rating' => 5,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [12],
                        ],
                        [
                            'name' => 'Elvive Oleo Extraordinario Nutrición Intensa',
                            'brand_id' => 6,
                            'image' => 'oleoextra.jpg',
                            'description' => 'Acondicionador con 6 óleos para nutrición intensa.',
                            'ingredients' => 'Óleos de flores, Glicerina',
                            'activos' => 'Óleos nutritivos',
                            'formato' => '400ml',
                            'rating' => 4,
                            'skin_types' => [1, 2, 3, 4, 5],
                            'concerns' => [12],
                        ],
                        [
                            'name' => 'Nécessaire Rosemary Leave-In Conditioner',
                            'brand_id' => 23,
                            'image' => 'necessaire-rosemary-conditioner.png',
                            'description' => 'Acondicionador leave-in fortalecedor con romero.',
                            'ingredients' => 'Rosemary Extract, Peptides',
                            'activos' => 'Romero',
                            'formato' => '200ml',
                            'rating' => 5,
                            'skin_types' => [1, 4],
                            'concerns' => [11, 14],
                        ],
                    ],
                ],
                'Tratamientos' => [
                    'description' => 'Productos para mejorar salud y fuerza del cabello.',
                    'products' => [
                        [
                            'name' => 'Olaplex No. 3 Hair Perfector',
                            'brand_id' => 17,
                            'image' => 'olaplex-n3.webp',
                            'description' => 'Tratamiento pre-shampoo reparador de enlaces.',
                            'ingredients' => 'Bis-Aminopropyl Diglycol Dimaleate',
                            'activos' => 'Molécula patentada',
                            'formato' => '100ml',
                            'rating' => 5,
                            'skin_types' => [1, 4],
                            'concerns' => [12],
                        ],
                        [
                            'name' => 'Moroccanoil Revitalizing Scalp Tonic',
                            'brand_id' => 29,
                            'image' => 'moroccanoil-scalp-tonic.jpg',
                            'description' => 'Tónico para cuero cabelludo y crecimiento.',
                            'ingredients' => 'Argania Spinosa Kernel Oil',
                            'activos' => 'Aceite de argán',
                            'formato' => '100ml',
                            'rating' => 4,
                            'skin_types' => [1],
                            'concerns' => [14],
                        ],
                    ],
                ],
            ],
            'Bodycare' => [
                'Hidratantes Corporales' => [
                    'description' => 'Productos para hidratar la piel del cuerpo.',
                    'products' => [
                        [
                            'name' => 'Nivea Milk Nutritiva Piel Seca',
                            'brand_id' => 18,
                            'image' => 'nivea-body-para-piel-extra-seca.jpg',
                            'description' => 'Leche corporal 48h hidratación para piel seca.',
                            'ingredients' => 'Aceite de almendras, Glicerina',
                            'activos' => 'Aceite de Almendras',
                            'formato' => 'Loción',
                            'rating' => 4,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 7, 9],
                        ],
                        [
                            'name' => 'Cetaphil Loción Hidratante Corporal',
                            'brand_id' => 19,
                            'image' => 'cetaphil-locion-hidratante.webp',
                            'description' => 'Loción ligera para piel sensible/irritada.',
                            'ingredients' => 'Glicerina, Aceite de Macadamia',
                            'activos' => 'Pantenol, Niacinamida',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 7, 9],
                        ],
                        [
                            'name' => 'CeraVe SA Body Lotion',
                            'brand_id' => 1,
                            'image' => 'cerave-sa-body.png',
                            'description' => 'Loción exfoliante con salicílico para piel áspera.',
                            'ingredients' => 'Salicylic Acid, Ceramides',
                            'activos' => 'Ácido Salicílico, Ceramidas',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3],
                        ],
                        [
                            'name' => 'La Roche-Posay Lipikar Lotion',
                            'brand_id' => 2,
                            'image' => 'la-roche-lipikar.jpg',
                            'description' => 'Loción reparadora 48h con niacinamida y karité.',
                            'ingredients' => 'Niacinamide, Shea Butter',
                            'activos' => 'Niacinamida, Manteca de Karité',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 9],
                        ],
                        [
                            'name' => 'Eucerin Advanced Repair Lotion',
                            'brand_id' => 11,
                            'image' => 'eucerin-advanced-repair.avif',
                            'description' => 'Loción reparadora para piel muy seca con urea.',
                            'ingredients' => 'Urea, Ceramides',
                            'activos' => 'Urea 5%',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2],
                            'concerns' => [3, 9],
                        ],
                        [
                            'name' => 'Aveeno Daily Moisturizing Lotion',
                            'brand_id' => 24,
                            'image' => 'aveeno-daily.png',
                            'description' => 'Loción hidratante diaria con avena coloidal.',
                            'ingredients' => 'Colloidal Oatmeal, Glycerin',
                            'activos' => 'Avena coloidal',
                            'formato' => 'Loción',
                            'rating' => 5,
                            'skin_types' => [2, 5],
                            'concerns' => [3, 9],
                        ],
                    ],
                ],
            ],
        ];

        foreach ($typesCategories as $typeName => $categories) {
            $type = Type::firstOrCreate(['name' => $typeName]);

            foreach ($categories as $categoryName => $categoryData) {
                $category = ProductCategory::updateOrCreate(
                    [
                        'name' => $categoryName,
                        'type_id' => $type->id,
                    ],
                    [
                        'slug' => Str::slug($categoryName),
                        'description' => $categoryData['description'] ?? null,
                    ]
                );

                foreach ($categoryData['products'] as $productData) {
                    $skinTypes = $productData['skin_types'] ?? [];
                    $concerns = $productData['concerns'] ?? [];
                    unset($productData['skin_types'], $productData['concerns']);

                    $product = Product::updateOrCreate(
                        ['name' => $productData['name']],
                        array_merge($productData, [
                            'type_id' => $type->id,
                            'category_id' => $category->id,
                            'image' => 'images/products/' . $productData['image'],
                        ])
                    );

                    $product->skinTypes()->sync($skinTypes);
                    $product->concerns()->sync($concerns);
                }
            }
        }
    }
}
